on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: acrnpfusiondev.azurecr.io
        username: ${{ secrets.acr_acrnpfusiondev_username }}
        password: ${{ secrets.acr_acrnpfusiondev_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/gatling-qps/docker" -f  "gatling-qps/docker/Dockerfile" -t acrnpfusiondev.azurecr.io/aksnpfusiondev:${{ github.sha }} --label dockerfile-path=gatling-qps/docker/Dockerfile
        docker push acrnpfusiondev.azurecr.io/aksnpfusiondev:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksnpfusiondev_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep fusion | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace fusion`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: fusion
        container-registry-url: acrnpfusiondev.azurecr.io
        container-registry-username: ${{ secrets.acr_acrnpfusiondev_username }}
        container-registry-password: ${{ secrets.acr_acrnpfusiondev_password }}
        secret-name: aksnpfusionddockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: fusion
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          acrnpfusiondev.azurecr.io/aksnpfusiondev:${{ github.sha }}
        imagepullsecrets: |
          aksnpfusionddockerauth
